#!/bin/sh
#
# @name IF750A Base
#
# @type Quadrotor x
# @class Copter
#

if [ $AUTOCNF = yes ]
then
	# Vehicle attitude PID tuning
	param set MC_AIRMODE 1
	param set MC_DTERM_CUTOFF 25
	param set MC_PITCHRATE_D 0.005
	param set MC_PITCHRATE_I 0.15
	param set MC_PITCHRATE_P 0.13
	param set MC_PITCHRATE_MAX 70
	param set MC_PITCH_P 5
	param set MC_ROLLRATE_D 0.005
	param set MC_ROLLRATE_I 0.15
	param set MC_ROLLRATE_P 0.13
	param set MC_ROLLRATE_MAX 70
	param set MC_ROLL_P 5
	param set MC_YAWRATE_I 0.2
	param set MC_YAWRATE_MAX 100
	param set MC_YAWRATE_P 0.4
	param set MC_YAW_P 2

	# Position Control Tuning
	# PID
	param set MPC_XY_VEL_P 0.14
	param set MPC_XY_VEL_D 0.005
	param set MPC_Z_VEL_P 0.3
	param set MPC_Z_VEL_I 0.35
	param set MPC_XY_P 0.6
	param set MPC_THR_HOVER 0.52
	param set MPC_THR_MIN 0.08
	# Limits
	param set MPC_MAN_TILT_MAX 25
	param set MPC_TILTMAX_AIR 25
	param set MPC_XY_VEL_MAX 8
	param set MPC_VEL_MANUAL 6
	param set MPC_XY_CRUISE 3
	param set MPC_MAN_Y_MAX 60
	# Setpoint generation
	param set MPC_POS_MODE 3
	param set MPC_AUTO_MODE 1
	param set MPC_YAW_MODE 3
	param set MPC_ACC_DOWN_MAX 1
	param set MPC_ACC_UP_MAX 2
	param set MPC_ACC_HOR 3
	param set MPC_ACC_HOR_MAX 3
	param set MPC_JERK_MIN 15
	param set MPC_JERK_MAX 20
	param set MPC_XY_TRAJ_P 1
	param set MPC_CRUISE_90 5
	# Stick
	param set MPC_XY_MAN_EXPO 0.7
	param set MPC_Z_MAN_EXPO 0.6
	param set MPC_YAW_EXPO 0.6
	# Takeoff/Land
	param set MPC_SPOOLUP_TIME 1
	param set MPC_TKO_RAMP_T 3
	param set MPC_LAND_SPEED 0.5

	# PWM parameters
	# defaults to reset deprecated configurations
	param set PWM_MIN 1000
	param set PWM_MAX 2000
	param set PWM_RATE 400
	param set SYS_USE_IO 1
	# enable SBUS output
	param set PWM_SBUS_MODE 1
	# thrust output curve compensation
	param set THR_MDL_FAC 0.5
	# PWM default values per channel
	param set PWM_AUX_DISARMED 900
	param set PWM_AUX_FAIL1 900
	param set PWM_AUX_FAIL2 900
	param set PWM_AUX_FAIL3 900
	param set PWM_AUX_FAIL4 900
	param set PWM_AUX_MIN 1050
	param set PWM_AUX_RATE 400
	param set PWM_MAIN_DIS1 2000
	param set PWM_MAIN_DIS3 1050
	param set PWM_MAIN_DIS4 1500
	param set PWM_MAIN_DIS5 900
	param set PWM_MAIN_FAIL3 1050
	param set PWM_MAIN_FAIL4 1500
	param set PWM_MAIN_FAIL5 2000

	# Sensors Parameters
	param set SENS_EN_LL40LS 2
	param set SENS_FLOW_MAXHGT 15
	param set IMU_GYRO_CUTOFF 40

	# MAVLink Parameters
	param set MAV_0_CONFIG 101
	param set MAV_0_FORWARD 1
	param set MAV_0_MODE 0
	param set MAV_0_RATE 1200
	param set MAV_1_FORWARD 1
	param set MAV_1_MODE 2
	param set MAV_1_RATE 100000
	param set SER_TEL1_BAUD 57600

	# Mount Parameters
	param set MNT_MODE_IN 0
	param set MNT_MODE_OUT 0
	param set MNT_RANGE_PITCH 180
	param set MNT_RANGE_ROLL 90

	# RTL Parameters
	param set RTL_DESCEND_ALT 5
	param set RTL_LAND_DELAY 0
	param set RTL_RETURN_ALT 30
	param set RTL_CONE_ANG 45

	# Logger Parameters
	param set SDLOG_DIRS_MAX 20
	param set SDLOG_MODE 0
	param set SDLOG_PROFILE 3

	# Camera Trigger
	param set TRIG_MODE 4
	param set TRIG_INTERFACE 3

	# Power Parametets
	param set BAT_N_CELLS 6
	param set BAT_A_PER_V 58
	param set BAT_V_CHARGED 4.2
	param set BAT_V_DIV 11.27
	param set BAT_CRIT_THR 0.35
	param set BAT_EMERGEN_THR 0.25
	param set BAT_LOW_THR 0.4

	# Circuit breakers
	param set CBRK_IO_SAFETY 22027

	# Commander Parameters
	param set COM_DISARM_LAND 1
	param set COM_LOW_BAT_ACT 3
	param set COM_RC_OVERRIDE 1
fi
