#!/bin/sh
#
# @name Avy Spec B
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer Peter Seres <peter@avy.eu>
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output AUX1 Right Elevon
# @output AUX2 Right Elevon Flipped
# @output AUX3 Left Elevon
# @output AUX4 Left Elevon Flipped
# @output AUX7 Pusher motor
# @output AUX8 Pusher reverse channel


sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF == yes ]
then

	param set CBRK_AIRSPD_CHK 162128
	param set CBRK_IO_SAFETY 22027
	param set CBRK_BUZZER 782097
	param set CBRK_VELPOSERR 201607

	param set COM_DISARM_LAND 5

	param set EKF2_GPS_POS_X -0.12
	param set EKF2_IMU_POS_X -0.12
	param set EKF2_TAU_VEL 0.5
	param set EKF2_GPS_P_GATE 10
	param set EKF2_GPS_V_GATE 10

	param set FW_ARSP_MODE 2
	param set FW_L1_PERIOD 25
	param set FW_MAN_P_MAX 30
	param set FW_MAN_R_MAX 50
	param set FW_PR_FF 0.7
	param set FW_PR_I 0.18
	param set FW_PR_P 0.15
	param set FW_PSP_OFF 5
	param set FW_P_LIM_MAX 15
	param set FW_P_LIM_MIN -25
	param set FW_P_RMAX_NEG 30
	param set FW_P_RMAX_POS 20
	param set FW_P_TC 0.5
	param set FW_RR_FF 0.9
	param set FW_RR_I 0.08
	param set FW_RR_IMAX 0.3
	param set FW_RR_P 0.23
	param set FW_R_LIM 35
	param set FW_R_RMAX 20
	param set FW_THR_ALT_SCL 2.7
	param set FW_THR_MIN 0.55
	param set FW_THR_SLEW_MAX 1
	param set FW_T_CLMB_MAX 3
	param set FW_T_HRATE_FF 0.5
	param set FW_T_HRATE_P 0.1
	param set FW_T_RLL2THR 20
	param set FW_T_SINK_MAX 3
	param set FW_T_SINK_MIN 1
	param set FW_THR_CRUISE 0.7
	param set FW_BAT_SCALE_EN	1
	param set FW_T_VERT_ACC 6

	param set IMU_GYRO_CUTOFF 30

	param set LNDMC_ALT_MAX 9999
	param set LNDMC_XY_VEL_MAX 1
	param set LNDMC_Z_VEL_MAX 0.7

	param set MC_AIRMODE 1
	param set MC_ACRO_P_MAX 150
	param set MC_ACRO_R_MAX 150
	param set MC_ACRO_Y_MAX 90
	param set MC_PITCHRATE_D 0.002
	param set MC_PITCHRATE_I 0.12
	param set MC_PITCHRATE_MAX 150
	param set MC_PITCHRATE_P 0.15
	param set MC_PITCH_P 5
	param set MC_ROLLRATE_D 0
	param set MC_ROLLRATE_I 0.19
	param set MC_ROLLRATE_MAX 150
	param set MC_ROLLRATE_P 0.23
	param set MC_ROLL_P 5
	param set MC_YAWRATE_D 0.0
	param set MC_YAWRATE_I 0.3
	param set MC_YAWRATE_MAX 90
	param set MC_YAWRATE_P 0.5
	param set MC_YAW_P 1.6

	param set MAV_1_CONFIG 102
	param set MAV_1_FORWARD 0
	param set MAV_1_MODE 2
	param set MAV_1_RATE 100000
	param set SER_TEL2_BAUD 1500000


	param set MPC_ACC_DOWN_MAX 4
	param set MPC_ACC_HOR_MAX 6
	param set MPC_ACC_UP_MAX 4
	param set MPC_HOLD_MAX_XY 1
	param set MPC_HOLD_MAX_Z 0.5
	param set MPC_JERK_MAX 8
	param set MPC_LAND_SPEED 1.2
	param set MPC_MAN_TILT_MAX 30
	param set MPC_MAN_Y_MAX 25
	param set MPC_POS_MODE 3
	param set MPC_SPOOLUP_TIME 1
	param set MPC_THR_HOVER 0.5
	param set MPC_THR_MAX 0.9
	param set MPC_THR_MIN 0.2
	param set MPC_TILTMAX_AIR 25
	param set MPC_TILTMAX_LND 25
	param set MPC_TKO_RAMP_T 0.8
	param set MPC_TKO_SPEED 1
	param set MPC_VEL_MANUAL 3
	param set MPC_XY_MAN_EXPO 0.75
	param set MPC_XY_P 0.8
	param set MPC_XY_TRAJ_P 0.5
	param set MPC_XY_VEL_I 0.04
	param set MPC_XY_VEL_MAX 5
	param set MPC_XY_VEL_P 0.1
	param set MPC_YAW_EXPO 0.6
	param set MPC_Z_MAN_EXPO 0.6
	param set MPC_Z_VEL_I 0.1
	param set MPC_Z_VEL_MAX_DN 1.5
	param set MPC_Z_VEL_MAX_UP 1.5

	param set RTL_TYPE 1

	param set VT_TYPE 2
	param set VT_MOT_COUNT 4
	param set VT_B_DEC_MSS 1.75
	param set VT_B_REV_DEL 1
	param set VT_B_REV_OUT 0.5
	param set VT_B_TRANS_DUR 8
	param set VT_B_TRANS_THR 0.7
	param set VT_DWN_PITCH_MAX 5
	param set VT_ELEV_MC_LOCK 0
	param set VT_FWD_THRUST_SC 2
	param set VT_FW_ALT_ERR 15
	param set VT_FW_MOT_OFFID 1234
	param set VT_FW_PERM_STAB 1
	param set VT_FW_QC_P 60
	param set VT_FW_QC_R 60
	param set VT_F_TRANS_THR 0.9
	param set VT_F_TR_OL_TM 10
	param set VT_IDLE_PWM_MC 1150
	param set VT_MOT_ID 1234
	param set VT_PSHER_RMP_DT 1
	param set VT_TRANS_MIN_TM 16
	param set VT_TRANS_TIMEOUT 22

	param set WV_EN 1
	param set WV_GAIN 1.4

fi

set MIXER quad_x
set PWM_OUT 1234
set PWM_RATE 400

set MIXER_AUX avy_specB_FMU
param set PWM_AUX_DIS7 900
param set PWM_AUX_DIS8 900

set MAV_TYPE 22
