#!/bin/sh
#
# IF750A drone with centered IMU on isolation plate
# 180 degrees yaw autopilot and 270 degrees yaw GPS.
# This vehicle doesn't enable Trimble GPS by default
#
# @name IF750A
#
# @type Quadrotor x
# @class Copter
#

sh /etc/init.d/rc.mc_defaults

set MIXER if750a_IO
set PWM_OUT 12345

set MIXER_AUX if750a_FMU
set PWM_OUT_AUX 1234

if [ $AUTOCNF = yes ]
then
	# Vehicle attitude PID tuning
	param set MC_DTERM_CUTOFF 25.0000
	param set MC_PITCHRATE_D 0.0050
	param set MC_PITCHRATE_I 0.6000
	param set MC_PITCHRATE_P 0.1900
	param set MC_PITCH_P 6.0000
	param set MC_ROLLRATE_D 0.0050
	param set MC_ROLLRATE_I 0.6000
	param set MC_ROLLRATE_P 0.1900
	param set MC_ROLL_P 6.0000
	param set MC_YAWRATE_I 0.2000
	param set MC_YAWRATE_MAX 100.0000
	param set MC_YAWRATE_P 0.4000
	param set MC_YAW_P 2.0000

	# Position Control Tuning
	param set MPC_POS_MODE 3
	param set MPC_ACC_DOWN_MAX 1
	param set MPC_ACC_HOR 3.000
	param set MPC_ACC_HOR_MAX 4.000
	param set MPC_AUTO_MODE 1
	param set MPC_JERK_MIN 15.0000
	param set MPC_JERK_MAX 20.0000
	param set MPC_MAN_Y_MAX 90.0000
	param set MPC_SPOOLUP_TIME 2.0000
	param set MPC_THR_HOVER 0.5200
	param set MPC_VEL_MANUAL 6.0
	param set MPC_XY_P 0.6
	param set MPC_XY_TRAJ_P 1.0000
	param set MPC_XY_VEL_MAX 8.0000
	param set MPC_XY_VEL_P 0.1400
	param set MPC_YAW_MODE 3
	param set MPC_Z_VEL_I 0.3500
	param set MPC_Z_VEL_P 0.3000
	param set MPC_LAND_SPEED 0.5000
	param set MPC_THR_MIN 0.0800
	param set MPC_TKO_RAMP_T 0.6000

	# EKF2 parameters
	param set EKF2_AID_MASK 33
	param set EKF2_BCOEF_X 45.0000
	param set EKF2_BCOEF_Y 45.0000
	param set EKF2_GPS_POS_X 0.1100
	param set EKF2_GPS_POS_Y 0.0000
	param set EKF2_GPS_POS_Z -0.1750
	param set EKF2_HGT_MODE 0
	param set EKF2_IMU_POS_X 0.0
	param set EKF2_IMU_POS_Y 0.0
	param set EKF2_IMU_POS_Z -0.075
	param set EKF2_OF_POS_X -0.1740
	param set EKF2_OF_POS_Z 0.0460
	param set EKF2_PCOEF_YN -0.3000
	param set EKF2_PCOEF_YP -0.1000
	param set EKF2_RNG_POS_X -0.1410
	param set EKF2_RNG_POS_Z 0.0440

	# PWM parameters
	param set PWM_AUX_DISARMED 900
	param set PWM_AUX_MIN 1050
	param set PWM_AUX_RATE 400
	param set PWM_MAIN_DIS3 1050
	param set PWM_MAIN_DIS4 1500
	param set PWM_MAIN_FAIL3 1050
	param set PWM_MAIN_FAIL4 1500
	param set PWM_MAX 1950
	param set PWM_MIN 1050
	param set PWM_RATE 400
	param set PWM_SBUS_MODE 1
	param set SYS_USE_IO 1

	# Sensors Parameters
	param set SENS_BOARD_ROT 4
	param set CAL_MAG0_ROT 6
	param set SENS_EN_LL40LS 2
	param set SENS_FLOW_MAXHGT 15.0000
	param set IMU_GYRO_CUTOFF 50.0000

	# MAVLink Parameters
	param set MAV_0_CONFIG 101
	param set MAV_0_FORWARD 1
	param set MAV_0_MODE 0
	param set MAV_0_RATE 1200
	# param set MAV_1_CONFIG 102
	param set MAV_1_FORWARD 1
	param set MAV_1_MODE 2
	param set MAV_1_RATE 100000
	param set SER_TEL1_BAUD 57600
	# param set SER_TEL2_BAUD 1500000

	# Mount Parameters
	#param set MNT_MODE_IN 0
	#param set MNT_MODE_OUT 0

	# Logger Parameters
	param set SDLOG_PROFILE 3

	# Camera Trigger
	param set TRIG_MODE 1
	param set TRIG_INTERFACE 3
	param set TRIG_PINS 56

	# GPS Parameters
	param set GPS_1_CONFIG 201
	param set SER_GPS1_BAUD 0

	# Power Parametets
	param set BAT_N_CELLS 6
	param set BAT_A_PER_V 36.3675
	param set BAT_CNT_V_CURR 0.0008
	param set BAT_CNT_V_VOLT 0.0008
	param set BAT_V_CHARGED 4.2000
	param set BAT_V_DIV 11.2700

	# Circuit breakers
	param set CBRK_IO_SAFETY 22027

	# Commander Parameters
	param set COM_DISARM_LAND 1

fi

# Forced parameters
param set MAV_1_CONFIG 102
param set SER_TEL2_BAUD 1500000
