#!/bin/sh
#
# @name Eiger Platform
#
# @type Quadrotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234

if [ $AUTOCNF = yes ]
then

	# Commander Parameters
	param set COM_OBS_AVOID 1
	param set COM_DISARM_LAND 0.5

	# EKF2 parameters
	param set EKF2_AID_MASK 33
	param set EKF2_GPS_POS_X 0.068
	param set EKF2_GPS_POS_Z -0.115
	param set EKF2_HGT_MODE 0
	param set EKF2_OF_POS_X 0.063
	param set EKF2_OF_POS_Z 0.025
	param set EKF2_REQ_HDRIFT 0.3
	param set EKF2_REQ_SACC 1
	param set EKF2_REQ_VDRIFT 0.3
	param set EKF2_RNG_AID 1
	param set EKF2_RNG_A_HMAX 8
	param set EKF2_RNG_A_VMAX 2
	param set EKF2_RNG_POS_X 0.035
	param set EKF2_RNG_POS_Z 0.025
	param set EKF2_PCOEF_XP -0.25
	param set EKF2_PCOEF_YN -0.55
	param set EKF2_PCOEF_YP -0.55

	# MAVLink parameters
	param set MAV_0_CONFIG 0
	param set MAV_1_CONFIG 102
	param set MAV_1_RATE 80000

	# Vehicle attitude PID tuning
	param set MC_ACRO_EXPO 0
	param set MC_ACRO_EXPO_Y 0
	param set MC_ACRO_P_MAX 200
	param set MC_ACRO_R_MAX 200
	param set MC_ACRO_SUPEXPO 0
	param set MC_ACRO_SUPEXPOY 0
	param set MC_ACRO_Y_MAX 150
	param set MC_DTERM_CUTOFF 60
	param set MC_PITCHRATE_D 0.001
	param set MC_PITCHRATE_I 0.1
	param set MC_PITCHRATE_MAX 200
	param set MC_PITCHRATE_P 0.06
	param set MC_ROLLRATE_D 0.001
	param set MC_ROLLRATE_I 0.1
	param set MC_ROLLRATE_MAX 200
	param set MC_ROLLRATE_P 0.06
	param set MC_YAWRATE_MAX 100
	param set MC_YRERR_CUTOFF 0

	# Position Control Tuning
	param set MPC_ACC_DOWN_MAX 2
	param set MPC_ACC_HOR_MAX 3
	param set MPC_ACC_UP_MAX 2
	param set MPC_POS_MODE 3
	param set MPC_COL_PREV_D 5
	param set MPC_IDLE_TKO 0
	param set MPC_MANTHR_MIN 0
	param set MPC_MAN_TILT_MAX 40
	param set MPC_MAN_Y_MAX 350
	param set MPC_TILTMAX_AIR 40
	param set MPC_THR_HOVER 0.3
	param set MPC_THR_MIN 0
	param set MPC_TKO_RAMP_T 0.6
	param set MPC_TKO_SPEED 1
	param set MPC_VEL_MANUAL 3
	param set MPC_XY_CRUISE 2.5
	param set MPC_XY_VEL_MAX 5
	param set MPC_XY_VEL_P 0.14
	param set MPC_XY_TRAJ_P 0.5
	param set MPC_Z_TRAJ_P 0.8
	param set MPC_Z_VEL_I 0.15
	param set MPC_Z_VEL_P 0.25
	param set MPC_SPOOLUP_TIME 2

	# Navigator Parameters
	param set NAV_ACC_RAD 1

	# PWM and RC Parameters
	param set PWM_MAX 1950
	param set PWM_MIN 1075
	param set RC_FLT_CUTOFF 0

	# RTL Parameters
	param set RTL_DESCEND_ALT 5
	param set RTL_LAND_DELAY 0
	param set RTL_RETURN_ALT 5

	# Logging Parameters
	param set SDLOG_PROFILE 1

	# Sensors Parameters
	param set SENS_BOARD_ROT 4
	param set SENS_CM8JL65_CFG 101
	param set SENS_FLOW_MAXHGT 25
	param set SENS_FLOW_MINHGT 0.5
	param set SENS_FLOW_ROT 2
	param set IMU_GYRO_CUTOFF 100

	# Power Parameters
	param set BAT_N_CELLS 4
	param set BAT_A_PER_V 36.3675
	param set BAT_CNT_V_CURR 0.0008
	param set BAT_CNT_V_VOLT 0.0008
	param set BAT_V_DIV 17.2860775

	# Circuit breakers
	param set CBRK_IO_SAFETY 22027
	param set CBRK_USB_CHK 197848

	param set THR_MDL_FAC 0.3
fi
