#!/bin/sh
#
# Auterion Base
#
# This script contains all the defaults for our internal vehicles.
#
# The critical parameters are
# MPC_POS_MODE to enable acceleration stick mapping in position mode
# MAV_1_CONFIG and SER_TEL2_BAUD to enable mavlink on companion link (TELEM2)
#

# RC mapping
. ${R}etc/extras/auterion_scripts/auterion_rc_mapping

# Position Mode Tuning
param set MPC_POS_MODE 4
param set MPC_ACC_DOWN_MAX 1
param set MPC_ACC_UP_MAX 2
param set MPC_ACC_HOR 3
param set MPC_ACC_HOR_MAX 3
param set MPC_VEL_MANUAL 6.0
param set MPC_XY_TRAJ_P 1

# MAVLink Parameters
param set MAV_0_CONFIG 101
param set MAV_0_FORWARD 1
param set MAV_0_MODE 0
param set MAV_0_RATE 1200
param set MAV_1_CONFIG 102
param set MAV_1_FORWARD 1
param set MAV_1_MODE 2
param set MAV_1_RATE 100000
param set MAV_1_RADIO_CTL 0
param set MAV_RADIO_TOUT 25
param set SER_TEL1_BAUD 57600
param set SER_TEL2_BAUD 1500000

# RTL Parameters
param set RTL_DESCEND_ALT 10
param set RTL_LAND_DELAY 0
param set RTL_RETURN_ALT 30

# Logger Parameters
param set SDLOG_DIRS_MAX 20

# Power Parametets
param set BAT_CRIT_THR 0.35
param set BAT_EMERGEN_THR 0.1
param set BAT_LOW_THR 0.4

# Circuit breakers
param set CBRK_IO_SAFETY 22027
