#!/bin/sh
#
# @name Auterion Base (multirotor)
#
# @class Copter
#

	# Position Control Tuning
	param set MPC_POS_MODE 3
	param set MPC_ACC_DOWN_MAX 1.0000
	param set MPC_ACC_UP_MAX 2.0000
	param set MPC_ACC_HOR 3.000
	param set MPC_ACC_HOR_MAX 3.000
	param set MPC_AUTO_MODE 1
	param set MPC_JERK_MIN 15.0000
	param set MPC_JERK_MAX 20.0000
	param set MPC_MAN_Y_MAX 60.0000
	param set MPC_SPOOLUP_TIME 2.0000
	param set MPC_VEL_MANUAL 6.0
	param set MPC_XY_P 0.6
	param set MPC_XY_TRAJ_P 1.0000
	param set MPC_XY_VEL_MAX 8.0000
	param set MPC_XY_VEL_D 0.005
	param set MPC_XY_VEL_P 0.1400
	param set MPC_XY_CRUISE 3.0000
	param set MPC_Z_VEL_I 0.3500
	param set MPC_Z_VEL_P 0.3000
	param set MPC_LAND_SPEED 0.5000
	param set MPC_TKO_RAMP_T 0.6000

	# MAVLink Parameters
	param set MAV_0_CONFIG 101
	param set MAV_0_FORWARD 1
	param set MAV_0_MODE 0
	param set MAV_0_RATE 1200
	param set MAV_1_CONFIG 102
	param set MAV_1_FORWARD 1
	param set MAV_1_MODE 2
	param set MAV_1_RATE 100000
	param set SER_TEL1_BAUD 57600
	param set SER_TEL2_BAUD 1500000

	# RTL Parameters
	param set RTL_DESCEND_ALT 10.0000
	param set RTL_LAND_DELAY 0.0000
	param set RTL_RETURN_ALT 30.0000

	# Logger Parameters
	param set SDLOG_DIRS_MAX 20
	param set SDLOG_MODE 0
	param set SDLOG_PROFILE 3

	# Power Parametets
	param set BAT_CRIT_THR 0.35
	param set BAT_EMERGEN_THR 0.10
	param set BAT_LOW_THR 0.40

	# Circuit breakers
	param set CBRK_IO_SAFETY 22027

	# Commander Parameters
	param set COM_DISARM_LAND 1

	# System Parameters
	param set SYS_FORCE_F7DC 2
