#!/bin/sh
#
# @name IF750A SITL
# InspiredFlight 750 Auterion edition. Gazebo Only.
#
# @type Quadrotor
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set EKF2_AID_MASK 3
	param set EKF2_EVP_NOISE 0.05
	param set EKF2_EVA_NOISE 0.05
	# param set EKF2_OF_POS_X -0.1740
	param set EKF2_OF_POS_Z 0.4300
	param set EKF2_HGT_MODE 1
	param set EKF2_PCOEF_XN -0.1000
	param set EKF2_PCOEF_XP -0.1000
	param set EKF2_PCOEF_YN -0.1000
	param set EKF2_PCOEF_YP -0.1000

	param set MPC_ALT_MODE 2

	param set TRIG_INTERFACE 3
	param set TRIG_MODE 4
	param set MNT_MODE_IN 0

fi

set MAV_TYPE 2

set MIXER quad_x
