#!/bin/sh
#
# @name Standard VTOL
#
# @type Standard VTOL
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set FW_L1_PERIOD 12

	param set MC_ROLLRATE_P 0.3

	param set MIS_TAKEOFF_ALT 10

	param set MPC_ACC_HOR_MAX 2
	param set MPC_XY_P 0.8
	param set MPC_XY_VEL_P_ACC 3
	param set MPC_XY_VEL_I_ACC 4
	param set MPC_XY_VEL_D_ACC 0.1

	param set NAV_ACC_RAD 5
	param set NAV_LOITER_RAD 80

	param set VT_F_TRANS_THR 0.75
	param set VT_MOT_ID 1234
	param set VT_FW_MOT_OFFID 1234
	param set VT_B_TRANS_DUR 8
	param set VT_TYPE 2

fi

set MAV_TYPE 22

set MIXER_FILE etc/mixers-sitl/standard_vtol_sitl.main.mix
set MIXER custom
