#!/bin/sh
#
# @name Standard VTOL with gimbal
#
# @type Standard VTOL with gimbal
#

sh /etc/init.d-posix/1040_standard_vtol

if [ $AUTOCNF = yes ]
then
	param set TRIG_INTERFACE 3
	param set TRIG_MODE 4
	param set MNT_MODE_IN 0

fi

set MAV_TYPE 22

set MIXER_FILE etc/mixers-sitl/standard_vtol_sitl.main.mix
set MIXER custom
